### ISSUE TITLE
sh[4012]: double free or corruption (out)

### ISSUE THREAD

**Issue by awais40** [AxisCommunications/acap-native-sdk-examples#160]
I updated my firmware from 11.1.72 to 11.6.89 for P3265 Camera, my application start to crash. It is working fine till firmware 11.1.72 but later firmware version had some memory leak that start to crash kernel. I was told that it was fixed in firmware 11.5x. When I tested on firmware 11.6.89, it did resolved the kernel crash but it is now given me following error when i call the following function 

```
loadedModel = larodLoadModel(conn, larodModelFd, LAROD_ACCESS_PRIVATE,
                                 "object_detection", &error);
```
 [Object Detection code ](https://github.com/AxisCommunications/acap-native-sdk-examples/blob/main/object-detection/app/object_detection.c)
at line 335.

<img width="777" alt="Screenshot 2023-09-21 142326" src="https://github.com/AxisCommunications/acap-native-sdk-examples/assets/36505095/cb1f1115-7c73-4798-ab1a-3821b909e3a5">

please also find my camera report in attachment.
[serverreport_cgi.txt](https://github.com/AxisCommunications/acap-native-sdk-examples/files/12684809/serverreport_cgi.txt)

**Comment by pataxis** [comment]
Hi @awais40 , thanks for reaching out.

Which ACAP SDK version have you used to build your application and which Larod API version have you specified?

> I was told that it was fixed in firmware 11.5x. 
Was this another reported issue here on this GitHub repo? If so, could you provide links to the issues for reference?
If it was through Axis support channels it's better that you file a new support ticket there.
