### ISSUE TITLE
How do you set which view from the camera should be used for e.g. object detection?

### ISSUE THREAD

**Issue by Equidem** [AxisCommunications/acap-native-sdk-examples#171]
Hi,
I am building an object detection app for Axis cameras using the native SDK,
basing it on the [object detection example](https://github.com/AxisCommunications/acap-native-sdk-examples/tree/main/object-detection) of this repository. However, I can't find anywhere how I can specify which view area should be used. I assume it should be somewhere in the VDO library, but its [API reference](https://axiscommunications.github.io/acap-documentation/docs/api/src/api/vdostream/html/annotated.html) contains no useful information (e.g. all the information provided for the VdoStream class is "A video stream") and [the older page which seems to have contained at least something](https://axiscommunications.github.io/acap-documentation/3.3/api/vdostream/html/vdo-channel_8h.html) (according to previews in Google search) doesn't exist anymore.
Could you please tell me how I can set the view area using the native SDK, or point me to a source containing that information in case I missed it somewhere?

**Comment by pataxis** [comment]
Hi @Equidem , thanks for your question!

The API documentation is unfortunately not greatly structured and the search functionality doesn't work. We hope to get a much better and searchable API documentation in the future.

In the left menu of the Video Capture API documentation (VDO), under **File List** you can get better information by clicking the header files, e.g. [vdo-channel.h](https://axiscommunications.github.io/acap-documentation/docs/api/src/api/vdostream/html/vdo-channel_8h.html), which I think correspond to "the older page".

In [vdo-stream.h](https://axiscommunications.github.io/acap-documentation/docs/api/src/api/vdostream/html/vdo-stream_8h.html) there's information of view areas (use browser search, often Ctrl+f, and search **view**) under the `channel` field that sounds like it could be what you look for.
