### ISSUE TITLE
using-opencv: example broken on armv7hf

### ISSUE THREAD

**Issue by tpatora** [AxisCommunications/acap-native-sdk-examples#194]
### Describe the bug

The example [using-opencv ](https://github.com/AxisCommunications/acap-native-sdk-examples/tree/main/using-opencv) seems broken on armv7hf. On ARTPEC-8 working without any issue.

**console log:** 

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/packages/opencv_app/lib/libopencv_core.so.4.5)

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/packages/opencv_app/opencv_app)

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/local/packages/opencv_app/lib/libopencv_core.so.4.5)

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/packages/opencv_app/lib/libopencv_core.so.4.5)

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/packages/opencv_app/lib/libopencv_imgproc.so.4.5)

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/packages/opencv_app/lib/libopencv_video.so.4.5)

[ INFO    ] opencv_app[15222]: /usr/local/packages/opencv_app/opencv_app: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/local/packages/opencv_app/lib/libopencv_core.so.4.5)

### Environment

Axis device model: Axis P1375
Axis device firmware version: 10.9.4

**Comment by pataxis** [comment]
Hi @tpatora , you have a compatibility mismatch. The latest SDK can't be used on older AXIS OS.

More info on [compatibility](https://axiscommunications.github.io/acap-documentation/docs/axis-devices-and-compatibility/#find-the-right-sdk-for-software-compatibility).
[Here](https://github.com/AxisCommunications/acap-native-sdk-examples/discussions/59)'s a longer explanation on compatibilty mismatch.
