### ISSUE TITLE
Deep learning Inference C++ example

### ISSUE THREAD

**Issue by ugrulas** [AxisCommunications/acap-native-sdk-examples#243]
Hello everyone,

I am currently working on a project that requires implementing deep learning inference in C++, and I'm seeking an example to help me get started. 

Thank you,

**Comment by Cacsjep** [comment]
Why not start with larod Object detection example?

**Comment by pataxis** [comment]
We have a quite new section in the ACAP documentation about [computer vision on Axis devices](https://axiscommunications.github.io/acap-documentation/docs/computer-vision-on-device/develop-your-own-deep-learning-application.html). I hope that can give you a background and point to relevant examples.
