### ISSUE TITLE
Error libm.so.6: version `GLIBC_2.38' & libstdc++.so.6: version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by Wiphat101** [AxisCommunications/acap-native-sdk-examples#272]
I tested the application using_opencv from the example https://github.com/AxisCommunications/acap-native-sdk-examples/tree/main/using-opencv
I haven't made any changes yet. When I test the .eap file with the camera, I get an error in the app log.
**Commands I use to build application**
docker build --tag <APP_IMAGE> .

Error #1
/usr/local/packages/opencv_app/opencv_app: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /usr/local/packages/opencv_app/lib/libopencv_imgproc.so.4.5)

Error #2
/usr/local/packages/opencv_app/opencv_app: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/local/packages/opencv_app/lib/libopencv_core.so.4.5)

![Error in log App OpenCv ](https://github.com/AxisCommunications/acap-native-sdk-examples/assets/130250528/b70b1ef2-61b8-4e40-8515-fa273ac6c271)

What causes this problem and what do I need to fix?

**Comment by Cacsjep** [comment]
Which camera Version and SDK Version you are using ?

**Comment by vivekatoffice** [comment]
I agree with @Cacsjep. You can find the [ACAP Native SDK software compatibility](https://axiscommunications.github.io/acap-documentation/docs/axis-devices-and-compatibility/#acap-native-sdk-software-compatibility) list

![image](https://github.com/AxisCommunications/acap-native-sdk-examples/assets/52032125/a43e803f-b87c-408b-b371-0a6b0902bf94)

**Comment by pataxis** [comment]
Hi @Wiphat101 , as both @Cacsjep  and @vivekatoffice  have hinted, this error is a compatibility issue.

This repository always show-case the use of the latest released ACAP Native SDK.
In the [compatibility](https://axiscommunications.github.io/acap-documentation/docs/axis-devices-and-compatibility/#acap-native-sdk-software-compatibility) table you can find which SDK to use for a certain AXIS OS version.

If you want to have example applications that work for a certain SDK release, go to the [Release](https://github.com/AxisCommunications/acap-native-sdk-examples/releases) page of this repo and click the tag to browse the repository at that point of time.

A more in-depth description of the compatibility issue can be found [here](https://github.com/AxisCommunications/acap-native-sdk-examples/discussions/59) before.
