### ISSUE TITLE
monkey.patch file seems to be broken in the web-server example.

### ISSUE THREAD

**Issue by lbRaytec** [AxisCommunications/acap-native-sdk-examples#278]
Hi,

I am trying to work with web-server example and could see that monkey.patch file seems to be broken. When I build the docker file, there are errors related to monkey server in creating the required files from the monkey.patch.

Refer the below image, especially, the last part where the function is incomplete.

![image](https://github.com/user-attachments/assets/29588f19-7750-4b50-b9b6-8b0a62f3a347)

**Comment by pataxis** [comment]
Hi @lbRaytec , thanks for reaching out.

Are you using the main branch of this repo or a tag?
Have you modified the example code? If so, have you tested to build with a clean repo and main branch?
What's your OS and build environment (e.g. Docker version)?
What's the build command and what's the error output?

In nightly tests I can see some warnings during build but no errors.
