### ISSUE TITLE
Web server monkey patch not working correctly.

### ISSUE THREAD

**Issue by richardpur** [AxisCommunications/acap-native-sdk-examples#36]
Error message with the default file.

../monkey.patch:46: space before tab in indent.
        GMainLoop *loop;
../monkey.patch:47: space before tab in indent.
        int ret;
../monkey.patch:52: space before tab in indent.
        loop = g_main_loop_new(NULL, FALSE);
../monkey.patch:53: space before tab in indent.
        write_index();
../monkey.patch:82: space before tab in indent.
        g_main_loop_run(loop);
error: corrupt patch at line 205

I attempted to fix the indent errors but still receiving the final error
error: corrupt patch at line 205

Can you help to advice the resolution for this?

**Comment by mikaelli-axis** [comment]
Just to make sure I have all the details, what SDK version are you using for this?

**Comment by mikaelli-axis** [comment]
I was able to build and run the web-server example as it is published (using the native-sdk v1.1) so I am closing this one.
