### ISSUE TITLE
Is it possible to develop a native app in python?

### ISSUE THREAD

**Issue by diolegend** [AxisCommunications/acap-native-sdk-examples#50]
Is it possible to develop a native app in python with an axis Q1952-E?

**Comment by diolegend** [comment]
> Thank you for reaching out, we'll get back to you shortly.

Thanks

**Comment by pataxis** [comment]
Hi again, I will just reiterate the answer from the other [issue tracker](https://github.com/AxisCommunications/acap-computer-vision-sdk-examples/issues/30) for computer vision examples where you the same question was raised.

> It is possible though the building of the Python interpreter using the native-sdk is non-trivial and not something we have official support for. It has been discussed but we have nothing to share about this at the moment.
