### ISSUE TITLE
Problem with installation: App with libtorch_cpu.so 108mb

### ISSUE THREAD

**Issue by diolegend** [AxisCommunications/acap-native-sdk-examples#60]
Hello,

I have a problem with AXIS Q1951-E Thermal Camera that has only 90 mb of space to install apps.

My app has a lib directory with libtorch_cpu.so 108mb.

I am wondering if is it possible to install an app on sd card?

**Comment by pataxis** [comment]
Hi @diolegend , thanks for the question.

It's not possible to install applications on SD Card today.
